apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: myrelease
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-01-29T14:10:29Z"
  generation: 1
  labels:
    app: dask
    app.kubernetes.io/managed-by: Helm
    chart: dask-2023.1.0
    component: scheduler
    heritage: Helm
    release: myrelease
  name: myrelease-dask-scheduler
  namespace: default
  resourceVersion: "754982"
  uid: eb0fd0f5-028e-4c91-b4ee-1fe361f438fe
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dask
      component: scheduler
      release: myrelease
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dask
        component: scheduler
        release: myrelease
    spec:
      containers:
      - args:
        - dask-scheduler
        - --port=8786
        - --dashboard-address=:8787
        image: ghcr.io/dask/dask:2023.1.0
        imagePullPolicy: IfNotPresent
        name: myrelease-dask-scheduler
        ports:
        - containerPort: 8786
          protocol: TCP
        - containerPort: 8787
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-01-29T14:10:33Z"
    lastUpdateTime: "2023-01-29T14:10:33Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-01-29T14:10:29Z"
    lastUpdateTime: "2023-01-29T14:10:33Z"
    message: ReplicaSet "myrelease-dask-scheduler-6bdc589cd7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
