apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: myrelease
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-01-29T14:10:28Z"
  labels:
    app: dask
    app.kubernetes.io/managed-by: Helm
    chart: dask-2023.1.0
    component: jupyter
    heritage: Helm
    release: myrelease
  name: myrelease-dask-jupyter
  namespace: default
  resourceVersion: "754875"
  uid: 7a7b14bf-120b-411b-b1ce-ce3f6ce5ee26
spec:
  clusterIP: 10.43.11.219
  clusterIPs:
  - 10.43.11.219
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: myrelease-dask-jupyter
    port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: dask
    component: jupyter
    release: myrelease
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
