apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: myrelease
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-01-29T14:10:29Z"
  generation: 7
  labels:
    app: dask
    app.kubernetes.io/managed-by: Helm
    chart: dask-2023.1.0
    component: worker
    heritage: Helm
    release: myrelease
  name: myrelease-dask-worker
  namespace: default
  resourceVersion: "969563"
  uid: c046b2ad-03c6-4b94-a0ce-61b0163d524b
spec:
  progressDeadlineSeconds: 600
  replicas: 6
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dask
      component: worker
      release: myrelease
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dask
        component: worker
        release: myrelease
    spec:
      containers:
      - args:
        - dask-worker
        - myrelease-dask-scheduler:8786
        - --no-dashboard
        - --dashboard-address
        - "8790"
        image: carloskez/dask_pyscenic
        imagePullPolicy: IfNotPresent
        name: myrelease-dask-worker
        ports:
        - containerPort: 8790
          name: dashboard
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 6
  conditions:
  - lastTransitionTime: "2023-01-29T14:10:29Z"
    lastUpdateTime: "2023-01-29T14:10:34Z"
    message: ReplicaSet "myrelease-dask-worker-589bdc487" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-01-30T10:04:00Z"
    lastUpdateTime: "2023-01-30T10:04:00Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 7
  readyReplicas: 6
  replicas: 6
  updatedReplicas: 6
