apiVersion: v1
kind: Service
metadata:
  name: nodeport-dask-ui
  namespace: default
spec:
  externalIPs:
  - 192.168.20.47
  ports:
  - nodePort: 32050
    port: 80
    protocol: TCP
    targetPort: 8787
    name: dask-webui
  selector:
    app: dask
    component: scheduler
    release: myrelease
  type: NodePort
status:
  loadBalancer: {}
