apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-prometheus
  namespace: monitoring
  labels:
    type: nfs
    app: prometheus-deployment
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-class
  nfs:
    server: 192.168.20.221
    path: "/mnt/nfs/promdata"
    readOnly: false