apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2023-01-27T15:00:23Z","labels":{"app":"dask","app.kubernetes.io/managed-by":"Helm","chart":"dask-2023.1.0","component":"jupyter","heritage":"Helm","release":"myrelease"},"name":"nodeport-jupyter","namespace":"default","resourceVersion":"246315","uid":"178c3a81-f8de-4aa4-9088-5206735859f8"},"spec":{"clusterIP":"10.43.85.39","clusterIPs":["10.43.85.39"],"externalIPs":["192.168.20.47"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"nodePort":30080,"port":80,"protocol":"TCP","targetPort":8888}],"selector":{"app":"dask","component":"jupyter","release":"myrelease"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2023-01-29T14:11:23Z"
  labels:
    app: dask
    app.kubernetes.io/managed-by: Helm
    chart: dask-2023.1.0
    component: jupyter
    heritage: Helm
    release: myrelease
  name: nodeport-jupyter
  namespace: default
  resourceVersion: "755135"
  uid: ca8ef981-7a8d-45cf-8f0d-918ed30e6e63
spec:
  clusterIP: 10.43.85.39
  clusterIPs:
  - 10.43.85.39
  externalIPs: []
    #- 192.168.20.47
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: dask
    component: jupyter
    release: myrelease
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
