apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"nodeport-dask-ui","namespace":"default"},"spec":{"externalIPs":["192.168.20.47"],"ports":[{"name":"dask-webui","nodePort":32050,"port":80,"protocol":"TCP","targetPort":8787}],"selector":{"app":"dask","component":"scheduler","release":"myrelease"},"type":"NodePort"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2023-02-04T22:50:47Z"
  name: nodeport-dask-ui
  namespace: default
  resourceVersion: "2396675"
  uid: a6e77f71-c592-4e68-97b4-f0ddf803e704
spec:
  clusterIP: 10.43.198.130
  clusterIPs:
  - 10.43.198.130
  externalIPs: []
    #- 192.168.20.47
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dask-webui
    nodePort: 32050
    port: 80
    protocol: TCP
    targetPort: 8787
  selector:
    app: dask
    component: scheduler
    release: myrelease
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
