apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-dask
  namespace: default
  labels:
    type: nfs
    app: dask-helm-chart
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-class
  nfs:
    server: 192.168.20.221
    path: "/mnt/nfs/databases"
    readOnly: false