apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: "2023-02-20T15:32:01Z"
  generation: 2
  name: demo-localhost
  namespace: default
  resourceVersion: "6551259"
  uid: c35f62ca-56f9-463d-903e-90e98517c685
spec:
  ingressClassName: nginx
  rules:
  - host: k8s-dk.mooo.com
    http:
      paths:
      - backend:
          service:
            name: demo
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - k8s-dk.mooo.com
    secretName: test-tls
status:
  loadBalancer:
    ingress:
    - ip: 192.168.20.159
